# This is a basic workflow to help you get started with Actions

name: Fg Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master,Dev ]
  pull_request:
    branches: [ master,Dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

# Build the application
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
 
 # upload apk name and download build artifact apk should be same (32,39)
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
         name: app
         path: app/build/outputs/apk/debug/app-debug.apk
  
# Download a Build Artifact
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
          name: app
          path: ${{github.workspace}}/signedrelease  
  
